package com.sixpack.dorundorun.infra.redis.stream.event;

public final class RedisStreamEventType {

	public static final String USER_REGISTERED = "USER_REGISTERED";
	public static final String PUSH_NOTIFICATION_REQUESTED = "PUSH_NOTIFICATION_REQUESTED";
	public static final String CHEER_NOTIFICATION_REQUESTED = "CHEER_NOTIFICATION_REQUESTED";
	public static final String CERTIFICATION_UPLOADED_NOTIFICATION_REQUESTED = "CERTIFICATION_UPLOADED_NOTIFICATION_REQUESTED";
	public static final String POST_REACTION_NOTIFICATION_REQUESTED = "POST_REACTION_NOTIFICATION_REQUESTED";
	public static final String CERTIFICATION_REMINDER_NOTIFICATION_REQUESTED = "CERTIFICATION_REMINDER_NOTIFICATION_REQUESTED";
	public static final String WEEKLY_RUNNING_PROGRESS_REMINDER_NOTIFICATION_REQUESTED = "WEEKLY_RUNNING_PROGRESS_REMINDER_NOTIFICATION_REQUESTED";
	public static final String NEW_USER_RUNNING_REMINDER_NOTIFICATION_REQUESTED = "NEW_USER_RUNNING_REMINDER_NOTIFICATION_REQUESTED";
	public static final String NEW_USER_FRIEND_REMINDER_NOTIFICATION_REQUESTED = "NEW_USER_FRIEND_REMINDER_NOTIFICATION_REQUESTED";

	private RedisStreamEventType() {
	}
}
